before:
  hooks:
  - go mod tidy
  - go generate ./...
  - sh scripts/completions.sh
  - sh scripts/manpages.sh
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  ldflags:
  - -X 'github.com/tantalor93/dnspyre/v2/cmd.Version={{.Version}}-{{ .Os }}-{{ .Arch }}'
archives:
- id: dnspyre
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  files:
  - LICENSE
  - README.md
  - completions/*
  - manpages/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
brews:
- tap:
    owner: tantalor93
    name: homebrew-dnspyre
  folder: Formula
  homepage: https://tantalor93.github.io/dnspyre/
  install: |-
    bin.install "dnspyre"
    bash_completion.install "completions/dnspyre.bash" => "_dnspyre"
    zsh_completion.install "completions/dnspyre.zsh" => "_dnspyre"
    man1.install Dir["manpages/*.1"]
dockers:
- use: docker
  id: dnspyre
  dockerfile: "Dockerfile-goreleaser"
  image_templates:
  - "tantalor93/dnspyre:{{ .Tag }}"
  - "tantalor93/dnspyre:v{{ .Major }}"
  - "tantalor93/dnspyre:v{{ .Major }}.{{ .Minor }}"
  - "tantalor93/dnspyre:latest"
