before:
  hooks:
  - go mod tidy
  - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  ldflags:
  - -X 'github.com/tantalor93/dnspyre/v2/cmd.Version={{.Version}}-{{ .Os }}-{{ .Arch }}'
archives:
- id: foo
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
brews:
- tap:
    owner: tantalor93
    name: homebrew-dnspyre
  folder: Formula
  homepage: https://github.com/Tantalor93/dnspyre
dockers:
- use: buildx
  id: dnspyre
  dockerfile: "Dockerfile-goreleaser"
  image_templates:
  - "tantalor93/dnspyre:{{ .Tag }}"
  - "tantalor93/dnspyre:v{{ .Major }}"
  - "tantalor93/dnspyre:v{{ .Major }}.{{ .Minor }}"
  - "tantalor93/dnspyre:latest"
