name: lint
on:
  pull_request:
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - uses: actions/checkout@v3
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      env:
        GOPROXY: proxy.golang.org,direct
      with:
        version: v1.49.0
  gosec:
    name: gosec
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: gosec
      uses: securego/gosec@master
      env:
        GOPROXY: proxy.golang.org,direct
      with:
        args: -conf=.gosec-conf.json ./...
